//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGKService {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class SGK : global::System.Configuration.ApplicationSettingsBase {
		
		private static SGK defaultInstance = ((SGK)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SGK())));
		
		public static SGK Default {
			get {
				return defaultInstance;
			}
		}
	}
}
